### ISSUE TITLE
OCP Support. Publish operator in OperatorHub.io

### ISSUE THREAD

**Issue by mmontes11** [mmontes11/mariadb-operator#10]
Make sure the operator behaves as expected in OCP, for example, by running the automated tests and then publish the operator in [OperatorHub](https://operatorhub.io/):
- https://operatorhub.io/contribute

More detailed instructions can be found in this [comment](https://github.com/mmontes11/mariadb-operator/issues/10#issuecomment-1301121910).

It's worth mentioning that, Openshift might require a different set of RBAC permissions:
- https://sdk.operatorframework.io/docs/faqs/#after-deploying-my-operator-why-do-i-see-errors-like-is-forbidden-cannot-set-blockownerdeletion-if-an-ownerreference-refers-to-a-resource-you-cant-set-finalizers-on-
- https://github.com/mmontes11/mariadb-operator/pull/18

**Comment by ctrought** [comment]
I'll just add there are two separate streams for OperatorHub. OpenShift comes with its own integrated version of OperatorHub. To publish it there would need to also submit this to the dedicated repo for community operators. This will make it available for install via OLM to all OCP + OKD users.

https://github.com/k8s-operatorhub/community-operators/tree/main/operators
https://github.com/redhat-openshift-ecosystem/community-operators-prod

Docs:
https://redhat-openshift-ecosystem.github.io/community-operators-prod/

**Comment by mmontes11** [comment]
Thanks for the detailed explanation @ctrought 🙏

Contributions are more than welcome and it seems that you have some expertise around this topic, so feel free to work on this and open a PR

**Comment by ctrought** [comment]
> Contributions are more than welcome and it seems that you have some expertise around this topic, so feel free to work on this and open a PR

Absolutely! If I can find some time I will submit a PR.

**Comment by ctml91** [comment]
Amazing 😍

**Comment by stefan-bergstein** [comment]
Great!!
