### ISSUE TITLE
Migrate chart to a public OCI registry like DockerHub

### ISSUE THREAD

**Issue by mmontes11** [mmontes11/mariadb-operator#20]
Migrate the operator helm chart to a public OCI registry. DockerHub has support for OCI artifacts already:
- https://www.docker.com/blog/announcing-docker-hub-oci-artifacts-support/

We should keep our old chartmuseum instance anyway so we can serve the chart for people using helm < 3.8

**Comment by mmontes11** [comment]
We have migrated our charts to be hosted in GitHub pages, so we no longer see availability issues due to the self-hosted chartmuseum, which was the main point of this issue. Closing

**Comment by sharovmerk** [comment]
@mmontes11 can you create OCI repository too, please? GHCR can be used for that
