### ISSUE TITLE
backup tries to mount mariadb-data volume which fails with ReadWriteOnce volumes

### ISSUE THREAD

**Issue by ibotty** [mmontes11/mariadb-operator#27]
<del>AFAICT it does not need the data dir.</del>

It does indeed need something.  Unfortunately I did not notice straight away because the job completed successfully but the log said
```
💾 Taking physical backup
[00] 2023-01-16 12:35:50 Connecting to MariaDB server host: mariadb, user: root, password: set, port: 3306, socket: /run/mysqld/mysqld.sock
[00] 2023-01-16 12:35:50 Using server version 10.10.2-MariaDB-1:10.10.2+maria~ubu2204
mariabackup based on MariaDB server 10.10.2-MariaDB debian-linux-gnu (x86_64)
[00] 2023-01-16 12:35:50 uses posix_fadvise().
[00] 2023-01-16 12:35:50 cd to /var/lib/mysql/
[00] 2023-01-16 12:35:50 open files limit requested 0, set to 1048576
[00] 2023-01-16 12:35:50 mariabackup: using the following InnoDB configuration:
[00] 2023-01-16 12:35:50 innodb_data_home_dir =
[00] 2023-01-16 12:35:50 innodb_data_file_path = ibdata1:12M:autoextend
[00] 2023-01-16 12:35:50 innodb_log_group_home_dir = ./
[00] 2023-01-16 12:35:50 InnoDB: Using liburing
2023-01-16 12:35:50 0 [Note] InnoDB: Number of transaction pools: 1
mariabackup: io_uring_queue_init() failed with ENOSYS: check seccomp filters, and the kernel version (newer than 5.1 required)
2023-01-16 12:35:50 0 [Warning] InnoDB: liburing disabled: falling back to innodb_use_native_aio=OFF
2023-01-16 12:35:50 0 [ERROR] InnoDB: File ./ib_logfile0 was not found
[00] 2023-01-16 12:35:50 Error: cannot read redo log header
🧹 Cleaning up old backups
📜 Backup history
```

This is not as successful as I hoped.

**Comment by mmontes11** [comment]
Thanks a lot for the feedback 🙏🏻 

The data dir is required when performing physical backups like [this](https://github.com/mmontes11/mariadb-operator/blob/main/config/samples/database_v1alpha1_backupmariadb_scheduled.yaml#L12) one. Those logs are from `backupmariadb`, which actually compains if the data dir is not mounted.

Could you provide more details of your test case so I can try to reproduce it?

**Comment by ibotty** [comment]
I don't know what details I should provide.  I tried not mounting `/var/lib/mysql/` by removing the volume in the cronjob.  But as you said, it does not work and can't.  Physical backups can't work without the physical files.  This should at least be documented.

I assume that taking a CSI snapshot of the volume (if supported) and mounting this file would be possible.

Is it possible to take a logical backup using the CRD?

**Comment by mmontes-f3** [comment]
You are not supposed to manipulate the resources managed by the operator, in this case the `Job`. If for some reason you want to achieve a different behaviour, you can open an issue so we can change the reconciliation logic to create those resources the way you think is better.

> This should at least be documented.

We are aware of this:
https://github.com/mmontes11/mariadb-operator/issues/21

> Is it possible to take a logical backup using the CRD?

Yes it is, you can either set `backup.scpec.physical = false` or not specifying it at all (defaults to false):
https://github.com/mmontes11/mariadb-operator/blob/main/config/samples/mariadb_v1alpha1_backup.yaml

Probably you are using the [scheduled](https://github.com/mmontes11/mariadb-operator/blob/main/config/samples/mariadb_v1alpha1_backup_scheduled.yaml) one from the samples maybe? That one is `physical

**Comment by mmontes11** [comment]
You are not supposed to manipulate the resources managed by the operator, in this case the `CronJob`/`Job`. If for some reason you want to achieve a different behaviour, you can open an issue so we can change the reconciliation logic to create those resources the way you think is better.

> This should at least be documented.

We are aware of this:
https://github.com/mmontes11/mariadb-operator/issues/21

> Is it possible to take a logical backup using the CRD?

Yes it is, you can either set `backup.scpec.physical = false` or not specifying it at all (defaults to false):
https://github.com/mmontes11/mariadb-operator/blob/main/config/samples/mariadb_v1alpha1_backup.yaml

Probably you are using the [scheduled](https://github.com/mmontes11/mariadb-operator/blob/main/config/samples/mariadb_v1alpha1_backup_scheduled.yaml) one from the samples maybe? That one is `physical`

Let me know if that solves your issue.

**Comment by ibotty** [comment]
You were right, that there was a `physical: true` which I did not notice :sweat_smile:.

Unfortunately  I updated the mariadb-operator-chart and have now an inconsistent installation (I'll file a separate issue).

Closing this issue.
