### ISSUE TITLE
chart broken: does not install CRDs

### ISSUE THREAD

**Issue by ibotty** [mmontes11/mariadb-operator#31]
They are included in the helm chart (in `mariadb-operator`/crds/crds.yaml`) and I am not using `--skip-crds`.  On this cluster I installed the operator before, so maybe the old CRDs are in conflict.  But deleting the CRDs and trying to reinstall via helm did not change anything.

**Comment by mmontes11** [comment]
Thanks for reporting this! We did some [changes](https://github.com/mmontes11/mariadb-operator/commit/6ae4b8eda19c857ec09d3beaa0a78cd54e7dcd47) in the CRDs in the latest release, but installing the latest version of the chart should be suffice. It's important to note that we are still in `v1alpha1` so according to[ Kubernetes API conventions](https://kubernetes.io/docs/reference/using-api/), APIs might change in incompatible way, sorry for any inconvenience anyway!

Can you update to the latest version of the chart?:
```bash
helm repo add mariadb-operator https://mmontes11.github.io/mariadb-operator
helm repo update
helm install mariadb-operator mariadb-operator/mariadb-operator --version 0.6.0
```

If it still not working, can you provide the logs of the operator?

**Comment by fabioportieri** [comment]
hello, i tried the following, after helm repo update:

C:\lavoro\workspace\fdp\kubernetes>helm upgrade --install mariadb-operator mariadb-operator/mariadb-operator --set metrics.enabled=true --set webhook.certificate.certManager=true --version 0.6.0


Release "mariadb-operator" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "mariadb-operator-webhook-cert" namespace: "" from "": no matches for kind "Certificate" in version "cert-manager.io/v1"
ensure CRDs are installed first, resource mapping not found for name: "mariadb-operator-selfsigned-issuer" namespace: "" from "": no matches for kind "Issuer" in version "cert-manager.io/v1"
ensure CRDs are installed first, resource mapping not found for name: "mariadb-operator" namespace: "" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "mariadb-operator-webhook" namespace: "" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first]

thank you

**Comment by mmontes11** [comment]
Hey there @fabioportieri !

You are choosing to install the recommended installation, which depends on [cert-manager ](https://cert-manager.io/docs/installation/) and [prometheus](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) CRDs, so you need to install them first in your cluster before proceeding to install `mariadb-operator`. Refer to this [section](https://github.com/mmontes11/mariadb-operator#recommended-installation) for more detail.

Alternatively, if you don't want to install external dependencies, you can go on with a bare minimum installation of `mariadb-operator`, take a look at this [section](https://github.com/mmontes11/mariadb-operator#bare-minimum-installation). 

Closing! feel free to reopen or create new issues if you need further help.
