### ISSUE TITLE
Error Creating Restore Job

### ISSUE THREAD

**Issue by parkerg21** [mmontes11/mariadb-operator#42]
1.6759603221844468e+09  ERROR   Reconciler error        {"controller": "restoremariadb", "controllerGroup": "database.mmontes.io", "controllerKind": "RestoreMariaDB", "restoreMariaDB": {"name":"restore","namesp: 1 error occurred:\n\t* error reconciling batch: error creating Job: jobs.batch \"restore\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: ,
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234

Looks Like fix is: (I'm still on old CRD naming convention)
- apiGroups:
  - database.mmontes.io
  resources:
  - restoremariadbs/finalizers
  verbs:
  - update

**Comment by mmontes11** [comment]
Thanks for reporting this @parkerg21 !

This is most likely an RBAC issue as you pointed out. I encourage you to upgrade to the latest version, as we are introducing significant improvements in this alpha version.

Anyway, could you confirm the following?
- Kubernetes version
- MariaDB operator version
- Installation flavour
   - Source: kubectl, helm or olm
   - Bare minimum or recommended
   
 Thanks for using MariaDB operator!

**Comment by parkerg21** [comment]
Sure, where can we see features being introduced in alpha version? The roadmap page?

OpenShift version: 4.10.0-0.okd-2022-05-28-062148
Kubernetes version: v1.23.5-rc.0.2071+3afdacbd018325-dirty
Channel: stable-4
MariaDB operator version: v0.0.5
Installation: kubectl and oc
Using argoCD for gitOps automation

**Comment by mmontes11** [comment]
> Sure, where can we see features being introduced in alpha version? The roadmap page?

The upcoming features can be checked in the [ROADMAP.md](https://github.com/mmontes11/mariadb-operator/blob/main/ROADMAP.md) , more to be added soon.

Then, regarding the issue, I've just submitted a patch to the helm chart to fix this, it should be published in [AftifactHub](https://artifacthub.io/packages/helm/mariadb-operator/mariadb-operator) and [OperatorHub](https://operatorhub.io/operator/mariadb-operator) shortly. Make sure you update to the `0.6.7`  version:
- https://github.com/mmontes11/mariadb-operator/pull/43

Closing! let me know if you need further help.
