### ISSUE TITLE
 mariadb_v1alpha1_mariadb_minimal.yaml fails

### ISSUE THREAD

**Issue by daniva6** [mmontes11/mariadb-operator#50]
Kubernetes version: microk8s  v1.26.1
mariadb-operator version: latest 
Install method: helm
Install flavour: minimal

kubectl apply -f config/samples/mariadb_v1alpha1_mariadb_minimal.yaml

kubectl describe pod/mariadb-0

Events:
  Type     Reason                  Age                From                     Message
  ----     ------                  ----               ----                     -------
  Normal   Scheduled               40s                default-scheduler        Successfully assigned mariadb-operator/mariadb-0 to kvmub02
  Normal   SuccessfulAttachVolume  39s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-06c18fac-12b5-4808-8b0d-9c4bee6849b9"
  Normal   Pulled                  11s (x3 over 31s)  kubelet                  Container image "mariadb:10.7.4" already present on machine
  Normal   Created                 11s (x3 over 31s)  kubelet                  Created container mariadb
  Normal   Started                 11s (x3 over 31s)  kubelet                  Started container mariadb
  Warning  BackOff                 7s (x7 over 29s)   kubelet                  Back-off restarting failed container mariadb in pod mariadb-0_mariadb-operator(96449cb0-be28-4855-89d3-4363d0217ece)

kubectl logs pod/mariadb-0

2023-02-28 15:29:32+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.7.4+maria~focal started.
2023-02-28 15:29:32+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2023-02-28 15:29:32+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.7.4+maria~focal started.
2023-02-28 15:29:32+00:00 [Note] [Entrypoint]: Initializing database files
2023-02-28 15:29:32 0 [ERROR] InnoDB: The Auto-extending data file './ibdata1' is of a different size 767 pages than specified by innodb_data_file_path
2023-02-28 15:29:32 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2023-02-28 15:29:33 0 [ERROR] Plugin 'InnoDB' init function returned error.
2023-02-28 15:29:33 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2023-02-28 15:29:33 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2023-02-28 15:29:33 0 [ERROR] Aborting

Installation of system tables failed!  Examine the logs in
/var/lib/mysql/ for more information.

The problem could be conflicting information in an external
my.cnf files. You can ignore these by doing:

    shell> /usr/bin/mariadb-install-db --defaults-file=~/.my.cnf

You can also try to start the mysqld daemon with:

    shell> /usr/sbin/mariadbd --skip-grant-tables --general-log &

and use the command line tool /usr/bin/mariadb
to connect to the mysql database and look at the grant tables:

    shell> /usr/bin/mysql -u root mysql
    mysql> show tables;

Try 'mysqld --help' if you have problems with paths.  Using
--general-log gives you a log in /var/lib/mysql/ that may be helpful.

The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
You can find the latest source at https://downloads.mariadb.org and
the maria-discuss email list at https://launchpad.net/~maria-discuss

Please check all of the above before submitting a bug report
at https://mariadb.org/jira

**Comment by mmontes11** [comment]
Hey! Thanks for reporting.

Could you delete the PVC and try recreating the `MariaDB` resource please?:

```bash
kubectl delete pvc storage-mariadb-0
kubectl apply -f config/samples/config
kubectl apply -f config/samples/mariadb_v1alpha1_mariadb_minimal.yaml
```

Thanks!

**Comment by mmontes11** [comment]
Hey @daniva6 sorry to hear that!

One more request from my side, could you provide the `StatefulSet` for your MariaDB instance so I can try to reproduce it? 

Something that comes from the top of my head is that the `storageClassName` user here is somehow not compatible with microk8s maybe?:
- https://github.com/mmontes11/mariadb-operator/blob/main/config/samples/mariadb_v1alpha1_mariadb_minimal.yaml#L21

If we don't resolve this problem, we can always raise an issue in the upstream image repo, as I'm not sure this is strictly related to the operator:
- https://github.com/MariaDB/server

**Comment by daniva6** [comment]
Hi @mmontes11,

I've changed the StorageClass to microk8s-hostpath and now it's working (before I used OpenEBS mayastor).

Maybe you can help me with another problem I'm encountering with mariadb. I'm getting the warning "Aborted connection .. to db: '...' user: 'root' host: '10.1.156.63' (Got an error reading communication packets)" - which parameters do I have to change?

Thank you for your support.

**Comment by mmontes11** [comment]
Great news! 🥳 

Closing!

> Maybe you can help me with another problem I'm encountering with mariadb. I'm getting the warning "Aborted connection .. to db: '...' user: 'root' host: '10.1.156.63' (Got an error reading communication packets)" - which parameters do I have to change?

Happy to help! Could you open a different issue for it?
Make sure you check the new `Connection` CRD:
- https://github.com/mmontes11/mariadb-operator/blob/main/config/samples/mariadb_v1alpha1_connection.yaml

**Comment by mmontes11** [comment]
Thanks for reporting this @kvaps ! Just [bumped](https://github.com/mariadb-operator/mariadb-operator/commit/014b4599507076e3cc206786a09552fee6c258e6) the examples.
