### ISSUE TITLE
warning "Aborted connection .. to db: '...' user: '...' host: '10.1.156.63' (Got an error reading communication packets)

### ISSUE THREAD

**Issue by daniva6** [mmontes11/mariadb-operator#52]
Kubernetes version: microk8s v1.26.1
mariadb-operator version: latest
Install method: helm
Install flavour: minimal

Hi, when I connect an application (fireflyiii) sometimes the warning "Aborted connection .. to db: '...' user: '...' host: '10.1.156.63' (Got an error reading communication packets)" appears. The application does not receive the expected data in that case.
Thank you for any help.

**Comment by mmontes11** [comment]
According to [this](https://dba.stackexchange.com/questions/19135/mysql-error-reading-communication-packets), raising `max_allowed_packet` most likely fixes this issue.

Specifying a custom `my.cnf`, and therefore `max_allowed_packet`, will be possible when this feature is implemented in the next release:
- https://github.com/mmontes11/mariadb-operator/issues/51

Will keep you in the loop

**Comment by daniva6** [comment]
thank you for your suggestion @mmontes11 
it seems like the problem surfaces when you have hugepages enabled, on a cluster without hugepages it works like a charm.

**Comment by mmontes11** [comment]
Hey @daniva6  !

The custom `my.cnf` feature has been eleased in the `v0.0.9`, make sure you update:
- https://github.com/mmontes11/mariadb-operator/releases/tag/v0.0.9
- https://github.com/mmontes11/mariadb-operator/releases/tag/helm-chart-0.9.0

This is something that can potentially fix the current issue. To do so, specify a custom `my.cnf` with the `max_allowed_packet` param, like in this example:
- https://github.com/mmontes11/mariadb-operator/blob/main/config/samples/mariadb_v1alpha1_mariadb.yaml#L31


Closing! Thanks for contributing to `mariadb-operator`
